// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmhnzuhvugyrhxqmsiyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtaG56dWh2dWd5cmh4cW1zaXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMzc5NDksImV4cCI6MjA3MzgxMzk0OX0.FI6QVgj3VMgIGl3LH2qt--sz7_wk4UluFqDOYo2O4uI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});